### ISSUE TITLE
export Class declaration not detected

### ISSUE THREAD

**Issue by guybedford** [incrementallair/es-navigation#10]
``` javascript
import { C } from 'file'
```

file.js

``` javascript
export class C {
}
```

**Comment by guybedford** [comment]
From - Unable to find definition of WebPageTranscoder in module /Users/guybedford/Projects/traceur-compiler/src/traceur.js /Users/guybedford/Projects/atom-symbol-navigation/build/search.js:101

**Comment by Bubblyworld** [comment]
Fixed.
