### ISSUE TITLE
When doing definition cycles ensure highlight around symbol is maintained

### ISSUE THREAD

**Issue by guybedford** [incrementallair/es-navigation#11]
Currently when it jumps back, the symbol isn't highlighted with the border around it.

**Comment by Bubblyworld** [comment]
Fixed.

**Comment by guybedford** [comment]
I'm still getting this?

**Comment by guybedford** [comment]
So I jump to the definition file, and it highlights the name, then I jump back, but the name isn't highlighted.

**Comment by Bubblyworld** [comment]
Indeed, the issue should be fixed properly  now.
